apiVersion: sift.axiom.dev/v1alpha1
kind: Sift
metadata:
  name: sift
  namespace: default
spec:
  image: REPLACE_ME__SIFT_IMAGE_DIGEST
  peerTlsSecret: REPLACE_ME__SIFT_PEER_TLS_SECRET
  replicasPerShard: 3
  voterCount: 3
  storage:
    storeSize: 50Gi
    controlSize: 5Gi
    gatewaySize: 2Gi
    querySize: 2Gi
  ingest:
    maxItemsPerMinute: 720000
    maxConcurrentRequests: 32
  auth: "off"
  gcpProjectId: REPLACE_ME__GCP_PROJECT_ID
  gkeClusterName: REPLACE_ME__GKE_CLUSTER_NAME
  gkeLocation: REPLACE_ME__GKE_LOCATION
